---
# file: site.yml

- hosts: glass_genesis
  become: yes
  vars:
    awx_version: 15.0.0
    docker_compose_version: 1.27.4

  roles:
  - glass-genesis

- hosts: glass_mcm
  become: yes

  roles:
  - glass-mcm
