---
- name: Install AWX
  hosts: glass_genesis
  become: true

  vars:
    awx_version: 15.0.1
    ansible_install_method: "pip"
    docker_install_compose: false
    pip_install_packages:
      - name: docker
      - name: docker-compose

  vars_files:
    - "~/.genesis_vars.yml"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: awx-firewalld
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - geerlingguy.git
    - geerlingguy.pip
    - geerlingguy.ansible
    - geerlingguy.docker
    - zorlin.awx
