---
- name: geerlingguy.repo-epel
- name: geerlingguy.git
- name: geerlingguy.ansible
- name: geerlingguy.docker
- name: geerlingguy.pip
- name: zorlin.awx
  src: https://github.com/Zorlin/ansible-role-awx
  version: master
