---
# Name: install dependencies on Ubuntu and Debian
# Does not yet work on Debian, sorry

- name: Software - Install some basic utilities
  apt:
    name:
      - git
      - screen
      - tmux
    state: present

- name: Software - Install the PPA utilities
  apt:
    name: software-properties-common
    state: present

- name: Sources - Install the official Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    update_cache: yes

- name: Software - Install the latest stable Ansible
  apt:
    name: ansible
    state: latest
