---
# Name: install dependencies on Ubuntu and Debian
# Does not yet work on Debian, sorry

- name: Software - Install some basic utilities
  apt:
    name:
      - git
      - screen
      - tmux
    state: present

- name: Software - Install the PPA utilities
  apt:
    name: software-properties-common
    state: present

- name: Sources - Ansible - Install the official Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    update_cache: yes

- name: Software - Ansible - Install the latest stable Ansible
  apt:
    name: ansible
    state: latest

- name: Software - Docker - Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Software - Docker - Trust Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Software - Docker - Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Software - Docker - Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Software - Python - Install Docker Python module
  apt:
    name: python3-docker
    state: present

- name: Software - Build Essential - Install make and other software needed for compiling
  apt:
    name: build-essential
    state: present

- name: Software - Git - Install Git (already handled by base, but just to be safe)
  apt:
    name: git
    state: present

- name: Software - Python - Install Python3.6+ (already handled above, but just to be safe)
  apt:
    name: python3
    state: present
