---
# Install all needed prerequisites for AWX

# Distro-specific tasks
# Ubuntu/Debian are the same for this role.
- include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

# More dependencies
- name: Software - docker-compose - Install docker-compose python module via pip
  pip:
    name: docker-compose
    executable: pip3

# Start and enable the Docker service
- name: Service - Start and enable Docker CE
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Groups - Add current user to the Docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
  when: "lookup('env', 'USER') != 'root'"

# Checkout the repo we need
- name: Git - Checkout AWX repo
  git:
    repo: https://github.com/ansible/awx.git
    version: '{{ awx_version }}'
    dest: '/home/wings/awx/'
  become: no
